campaign/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin

from wagtail.admin import urls as wagtailadmin_urls
from wagtail.core import urls as wagtail_urls
from wagtail.documents import urls as wagtaildocs_urls
from django.urls import path, re_path

from search import views as search_views

urlpatterns = [
    url(r'^dashboard-admin/', admin.site.urls),

    url(r'^admin/', include(wagtailadmin_urls)),
    url(r'^documents/', include(wagtaildocs_urls)),

    url(r'^search/$', search_views.search, name='search'),

    # For anything not caught by a more specific rule above, hand over to
    # Wagtail's page serving mechanism. This should be the last pattern in
    # the list:
    url(r'', include(wagtail_urls)),

    # Alternatively, if you want Wagtail pages to be served from a subpath
    # of your site, rather than the site root:
    #    url(r'^pages/', include(wagtail_urls)),
]


if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns

    # Serve static and media files from development server
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
import json, random

from django.conf import settings
from django import forms

from django.contrib.auth.backends import ModelBackend
from django.contrib.auth.models import User
from django.core.serializers.json import DjangoJSONEncoder
from django.db import models
from django.shortcuts import render, redirect, get_object_or_404



from wagtail.contrib.forms.models import AbstractForm, AbstractEmailForm, AbstractFormField, AbstractFormSubmission
from wagtail.core import blocks
from wagtail.core.fields import RichTextField, StreamField
from wagtail.core.models import Page, PageBase
from wagtail.images.edit_handlers import ImageChooserPanel
from wagtail.admin.edit_handlers import (FieldPanel, FieldRowPanel,
                                         InlinePanel, MultiFieldPanel,
                                         StreamFieldPanel)

from home.blocks import VideoIdsBlock
#from home.forms import videoUploadForm
from modelcluster.fields import ParentalKey

class VideoData(models.Model):
    uploader = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=80, blank=False, null=True)
    #make into public/private repo
    video = models.FileField() 

    def __str__(self):
        return self.name

#was unable to use it within forms.py for some reason
class videoUploadForm(forms.ModelForm):

    class Meta:
        model = VideoData
        fields = ['name', 'video']


class PasswordlessAuthBackend(ModelBackend):
    def authenticate(self, username=None):
        try:
            return User.objects.get(username=username)
        except User.DoesNotExist:
            return None

        def get_user(self, user_id):
            try:
                return User.objects.get(pk=user_id)
            except User.DoesNotExist:
                return None


    '''
    name = models.CharField(max_length=250, null=True, blank=False)
    email = models.EmailField(max_length=250, null=True, blank=False)

    def __str__(self):
        return self.name
'''

class VideoSubmission(Page):
    headline = models.CharField(max_length=200, null=True, blank=True)
    intro_video_id = models.CharField(max_length=50, null=True, blank=True)
    background_image = models.ForeignKey(
        'wagtailimages.Image',
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='+'
    )
    video_ids = StreamField([('video_ids', VideoIdsBlock())], null=True, blank=True)


    content_panels = Page.content_panels + [
        FieldPanel('headline'),
        FieldPanel('intro_video_id'),
        ImageChooserPanel('background_image'),
        StreamFieldPanel('video_ids'),

    ] 

    def serve(self, request):

        if request.method == 'GET':
            form = videoUploadForm()
            #retreiving user from session variables
            new_user_username = request.session.get('new_user_username', None)
            try:
                new_user = User.objects.get(username=new_user_username)
                arg = {
                'new_user':new_user,
                'page': self,
                'form': form,
                }
            except User.DoesNotExist:
                arg = {'page': self}
            request.session['new_user'] = None
        elif request.method == 'POST':
            arg = {'page': self, 'new_user': request.user}
            form = videoUploadForm(request.POST)
            print (form)
            _user = request.POST.get('user')
            print (_user)
            if form.is_valid():
                form.save(commit=False)
                try:
                    user = User.objects.get(username=_user)
                except User.DoesNotExist:
                    user = None
                name = form.cleaned_data['name']
                video = form.cleaned_data['video']
                form.save()
                arg = {
                'form': videoUploadForm(),
                'page': 'self',
                'new_user': request.user,
                'success': True,
                }
                return render(request, 'home/video_submission.html', arg)
            else:
                errors = form.errors
                print (errors)
                error_list = []
                counter = 0
                for error in errors:
                    error_list.append([error])
                    for error_detail in errors[error]:
                        error_list[counter].append(error_detail)
                    counter += 1
                print ('errors list: {}'.format(error_list))
                arg = {
                'form': videoUploadForm(),
                'page': self,
                'new_user': request.user,
                'errors': error_list,
                }                
        return render(request, 'home/video_submission.html', arg)


class HomePage(Page):
    headline = models.CharField(max_length=200, null=True, blank=True)
    intro_video_id = models.CharField(max_length=50, null=True, blank=True)
    background_image = models.ForeignKey(
        'wagtailimages.Image',
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='+'
    )
    thank_you_page_title = models.CharField(max_length=200, null=True, blank=True)

    thank_you_text = RichTextField(blank=True)

    content_panels = Page.content_panels + [
        FieldPanel('headline'),
        FieldPanel('intro_video_id'),
        ImageChooserPanel('background_image'),
        FieldPanel('thank_you_text'),
        FieldPanel('thank_you_page_title'),

    ] 

    def serve(self, request):
        from home.forms import UserCreateForm

        if request.method == 'POST':
            form = UserCreateForm(request.POST)
            if form.is_valid():
                email = form.cleaned_data['email']
                _username = '{}_{}'.format(form.cleaned_data['first_name'], form.cleaned_data['last_name'])

                #creating uniqe username
                unique = False
                while not(unique):
                    if User.objects.filter(username=_username).exists():
                        _username += '{}'.format(random.randint(0,999))
                    else:
                        #if it's unique then create user
                        unique = True
                        p, created = User.objects.get_or_create(
                            username = _username,
                            email = email,
                            defaults={
                            'first_name':form.cleaned_data['first_name'],
                            'last_name':form.cleaned_data['last_name']
                            })

                print (p)
                #getting the redirect link if there is one
                home_page_obj = HomePage.objects.first()
                video_submission_page = VideoSubmission.objects.descendant_of(home_page_obj).first()
                if video_submission_page:
                    direct_url = '/{}/'.format(str(video_submission_page).replace(' ', '-')).lower() # adding / and replacing spacing with - while making it all lowercase

                    #adding new user as a session variable to be accessed later
                    request.session['new_user_username'] = p.username
                    #redirecting to video submition page
                    return redirect(direct_url)


                return render(request, 'home/video_submission.html', {
                                    'page': self,
                                    'user':p,})
        else:
            form = UserCreateForm()
        return render(request, 'home/home_page.html', {
            'page': self,
            'form': form
            })


    #if user has already exists
    '''
    #serve is like the basic view in views.py
    def serve(self, request, *args, **kwargs):
        if self.get_submission_class().objects.filter(page=self, 
            email=request.user.pk).exists():
                return render(
                    request,
                    self.template,
                    self.get_context(request)
                    )
    '''



    #using own submission class
    def get_submission_class(self):
        return CustomFormSubmission

    def process_form_submission(self, form):
        self.get_submission_class().objects.create(
            form_data=json.dumps(form.cleaned_data, cls=DjangoJSONEncoder),
            page=self, email=form.cleaned_data['email']
            )

#own class
class CustomFormSubmission(AbstractFormSubmission):
    email = models.EmailField(max_length=100, blank=False)

'''
to use with previous to stop multiple same emails being used
    class Meta:
        unique_together = ('page', 'email')
'''

home/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _


from home.models import VideoData


class videoUploadForm(forms.ModelForm):

	class Meta:
		model = VideoData
		fields = ['name', 'video']

class UserCreateForm(UserCreationForm):
	email = forms.EmailField(required=True)

	class Meta:
	    model = User
	    fields = ('first_name','last_name','username','email', 'password1', 'password2')

	    labels = {
	    'last_name': _('Last name (optional)'),
	    }

	def __init__(self, *args, **kwargs):
	    super(UserCreateForm,self).__init__(*args, **kwargs)
	    #remove what you like...
	    #self.fields.pop('first_name')
	    self.fields.pop('username')
	    self.fields.pop('password1')
	    self.fields.pop('password2')

'''
	def save(self, commit=True):
		user = super(UserCreateForm, self).save(commit=False)
		clean_email = self.cleaned_data['email']
		user.email = clean_email
		user.username = self.cleaned_data['username']
		if commit:
			user.save()
		return user
class videoUploaderForm(forms.ModelForm):

	class Meta:
		model = videoUploader
		fields = ['name', 'email']'''

home/templates/home/home_page.html
{% extends "base.html" %}
{% load static i18n wagtailcore_tags wagtailuserbar wagtailimages_tags widget_tweaks %}

{% block body_class %}template-homepage{% endblock %}

{% block extra_css %}
<style type="text/css">
	html{
	{% if page.background_image %}
		{% image page.background_image original as background_image %}
			background:url({{ background_image.url }}) no-repeat center center fixed;
		  -webkit-background-size: cover;
		  -moz-background-size: cover;
		  -o-background-size: cover;
		  background-size: cover;
	{% else %}
			background-color: black;
		}
{% endif %}
</style>
    <link href="{% static 'css/welcome_page.css' %}" rel="stylesheet">
{% endblock extra_css %}

{% block content %}

<div class="centre-block">
	<div class="container inner-block">
		
<h1 class="text-info headline">{{ page.headline }}</h1>
{% if page.intro_video_id %}
<div class="intro-video">
	<iframe id="intro-video-frame" width="560" height="315" src="https://www.youtube-nocookie.com/embed/{{ page.intro_video_id }}?controls=1" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</div>
{% endif %}
{% if form %}
	<form action="{% pageurl page %}" method="POST">
	{% csrf_token %}
		<div class="row mx-1" style="justify-content: center">
			
		{% include 'bf_forms.html' with form=form %}
		</div>
	<input class='btn btn-info btn-block'type="submit" value="Join the movement!">
	</form>

{% else %}
	<h4>You can only fill in the form once</h4>
{% endif %}
	</div>
	
</div>	
{% endblock content %}


<!-- Scripts -->
{% block extra_js %}

<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js">
</script>
<script src="{% static 'js/fitText/jquery.fittext.js' %}"></script>
<script type="text/javascript">
	$(function(){
		$(".headline").fitText(1.4);
		var vid_width = $("#intro-video-frame").width()
		$("#intro-video-frame").height((vid_width*0.5))
	})
</script>

{% endblock %}

home/templates/home/home_page_landing.html
{% extends 'base.html' %}

{% block content %}
<h1> Success! </h1>
{% endblock %}

home/templates/home/video_submission.html
{% extends "base.html" %}
{% load static i18n wagtailcore_tags wagtailuserbar wagtailimages_tags widget_tweaks %}

{% block body_class %}template-submition-page{% endblock %}

{% block extra_css %}
<style type="text/css">
	html{
	{% if page.background_image %}
		{% image page.background_image original as background_image %}
			background:url({{ background_image.url }}) no-repeat center center fixed;
		  -webkit-background-size: cover;
		  -moz-background-size: cover;
		  -o-background-size: cover;
		  background-size: cover;
	{% else %}
			background-color: black;
		}
{% endif %}
</style>
    <link href="{% static 'css/welcome_page.css' %}" rel="stylesheet">
    <link href="{% static 'css/fancy_btn.css' %}" rel="stylesheet">
{% endblock extra_css %}

{% block content %}

<div class="video-centre-block">
	<div class="container inner-block">
		
{% if success %}
	<div class="alert alert-info">
	<h2>Success!</h2>
	<p>We have recieved your entry</p>
	</div>
{% endif %}

{% if errors %}
	<div class="alert alert-danger" style="text-align: left;">
	<h2>Oh No!</h2>
	<p>We had some errors. Check the following fields:</p>
	{% for error in errors %}
	<ul>
	{% for detail in error %}
		{% if forloop.first %}
		<li>{{ detail }}</li>
		{% else %}
		<ul>
			<li>{{ detail }}</li>
		</ul>
		{% endif %}
		{% endfor %}
		{% endfor %}
		</ul>
	</div>
{% endif %}
<!-- main video	
{% if page.intro_video_id %}
<div id="intro-video">
	<iframe id="intro-video-frame" width="560" height="315" src="https://www.youtube-nocookie.com/embed/{{ page.intro_video_id }}?controls=1" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</div>
{% endif %}
For video in video --->
<h1 class="text-info headline">{{ page.headline }}</h1>

{% if page.intro_video_id %}
<div class="intro-video">
	<iframe id="grid-intro-video-frame" src="https://www.youtube-nocookie.com/embed/{{ page.intro_video_id }}?controls=1" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</div>
{% endif %}


<div class="container" style="justify-content: center">
	
<div class="row" style="width: 100%; justify-content: center;margin: 0 auto">
	
	{% with blocks=page.video_ids %}
	{% for block in blocks %}
		{{ block }}
	{% endfor %}
	{% endwith %}
</div>
</div>

<button id="video-modal-btn" class="fancy-btn btn-info">Submit your opinion!</button>

<div id="videoModal" class="modal">
	<div class="modal-content">
		<span id="video_modal_close" class="close">&times;</span>
		{% if form %}
			<form action="{% pageurl page %}" method="POST">
			{% csrf_token %}
			<div class="row mx-1" style="justify-content: center">

				{% include 'bf_forms.html' with form=form %}
				<input type="hidden" name="user" value='{{ new_user.username }}'>
			</div>
			<input class='fancy-btn btn-info btn-block'type="submit" value="Share the wonder!">
			</form>

			{% else %}
				<h4>You can only fill in the form once</h4>
		{% endif %}
	</div>
</div>
</div>
	
</div>	
{% endblock content %}


<!-- Scripts -->
{% block extra_js %}

<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js">
</script>
<script src="{% static 'js/fitText/jquery.fittext.js' %}"></script>
<script src="{% static 'js/fancy_btn.js' %}"></script>
<script type="text/javascript">
	$(function(){
		$(".headline").fitText(1.4);
		var vid_grid_width = $(".grid-video-frame").width()
		$(".grid-video-frame").height((vid_grid_width*0.6))
		var vid_intro_grid_width = $("#grid-intro-video-frame").width()
		$("#grid-intro-video-frame").height((vid_intro_grid_width*0.6))

		//improving upload file button
		$('#id_video').addClass('fancy_btn')

		//bmodal
		//get modal
		var modal = $('#videoModal');

		//get btn opening modal
		var modal_btn = $('#video-modal-btn');

		//get <span> element that closes modal
		var span = $('#video_modal_close');

		//when user clicks on btn open modal

	modal_btn.click(function(){
	$('#videoModal').css("display","block");
	})

	//when user clicks on (x) close modal
	span.click(function(){
	$('#videoModal').css("display","none");
	})
	//if user clicks anywhere else close modal
	$(window).click(function(event){
		var modal_display = $('#videoModal').css('display')
//	if ((modal_display =='block')){
//		console.log('block')
//		if (!(event.target == $('#videoModal'))){
//			console.log('got here')
//			$('#videoModal').css("display","none");
//		}
	//}
	console.log(event.target);
	if (event.target.id == $('#videoModal').attr('id')){
		$('#videoModal').css("display","none");
	}
	})
})
</script>

{% endblock %}